// Copyright 2026 github.com/gagliardetto
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package solana

import (
	"bytes"
	"encoding/hex"
	"os"
	"testing"

	bin "github.com/gagliardetto/binary"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// txErrFixture is one entry of testdata/transaction_error_fixtures.json,
// generated by a Rust helper pinned to solana-transaction-error 3.1.0 and
// solana-instruction-error 2.2.0: for each variant the Rust {:?} rendering,
// Display rendering, bincode bytes (hex), and serde JSON.
type txErrFixture struct {
	Kind    string `json:"kind"`
	Debug   string `json:"debug"`
	Display string `json:"display"`
	Bincode string `json:"bincode"`
	JSON    string `json:"json"`
}

func loadTxErrFixtures(t *testing.T) []txErrFixture {
	t.Helper()
	data, err := os.ReadFile("testdata/transaction_error_fixtures.json")
	require.NoError(t, err)
	var fixtures []txErrFixture
	require.NoError(t, json.Unmarshal(data, &fixtures))
	require.NotEmpty(t, fixtures)
	return fixtures
}

// jsonEq compares two JSON documents structurally.
func jsonEq(t *testing.T, want, got string) {
	t.Helper()
	var w, g interface{}
	require.NoError(t, json.Unmarshal([]byte(want), &w))
	require.NoError(t, json.Unmarshal([]byte(got), &g))
	assert.Equal(t, w, g)
}

// TestTransactionErrorFixtures pins the Go codecs against the Rust SDK for
// every variant of both enums: bincode decode/encode round-trip, Debug and
// Display renderings, and serde JSON in both directions.
func TestTransactionErrorFixtures(t *testing.T) {
	for _, fx := range loadTxErrFixtures(t) {
		t.Run(fx.Kind+"/"+fx.Debug, func(t *testing.T) {
			raw, err := hex.DecodeString(fx.Bincode)
			require.NoError(t, err)

			switch fx.Kind {
			case "instruction":
				var e InstructionError
				dec := bin.NewBinDecoder(raw)
				require.NoError(t, e.UnmarshalWithDecoder(dec))
				require.Zero(t, dec.Remaining(), "trailing bytes after decode")

				assert.Equal(t, fx.Debug, e.DebugString())
				assert.Equal(t, fx.Display, e.Error())

				buf := new(bytes.Buffer)
				require.NoError(t, e.MarshalWithEncoder(bin.NewBinEncoder(buf)))
				assert.Equal(t, fx.Bincode, hex.EncodeToString(buf.Bytes()))

				gotJSON, err := e.MarshalJSON()
				require.NoError(t, err)
				jsonEq(t, fx.JSON, string(gotJSON))

				var back InstructionError
				require.NoError(t, back.UnmarshalJSON([]byte(fx.JSON)))
				assert.Equal(t, e, back)

			case "transaction":
				e, err := DecodeTransactionError(raw)
				require.NoError(t, err)

				assert.Equal(t, fx.Debug, e.DebugString())
				assert.Equal(t, fx.Display, e.Error())

				reenc, err := e.MarshalBinary()
				require.NoError(t, err)
				assert.Equal(t, fx.Bincode, hex.EncodeToString(reenc))

				gotJSON, err := e.MarshalJSON()
				require.NoError(t, err)
				jsonEq(t, fx.JSON, string(gotJSON))

				var back TransactionError
				require.NoError(t, back.UnmarshalJSON([]byte(fx.JSON)))
				assert.Equal(t, *e, back)

			default:
				t.Fatalf("unknown fixture kind %q", fx.Kind)
			}
		})
	}
}

func TestTransactionErrorLegacyBorshIoJSON(t *testing.T) {
	// SDKs before instruction-error 2.2.0 serialized BorshIoError with a
	// string payload; RPC nodes running them still emit this form.
	var ie InstructionError
	require.NoError(t, ie.UnmarshalJSON([]byte(`{"BorshIoError":"failed"}`)))
	assert.Equal(t, InstrErrBorshIoError, ie.Type)
	assert.Equal(t, "failed", ie.BorshIoMessage)

	var te TransactionError
	require.NoError(t, te.UnmarshalJSON([]byte(`{"InstructionError":[2,{"BorshIoError":"oops"}]}`)))
	assert.Equal(t, TxErrInstructionError, te.Type)
	assert.Equal(t, uint8(2), te.InstructionIndex)
	require.NotNil(t, te.InstructionError)
	assert.Equal(t, InstrErrBorshIoError, te.InstructionError.Type)
	assert.Equal(t, "oops", te.InstructionError.BorshIoMessage)
}

func TestTransactionErrorDecodeRejects(t *testing.T) {
	// Unknown variant tags must error rather than mis-map.
	_, err := DecodeTransactionError([]byte{0x99, 0, 0, 0})
	require.Error(t, err)

	// Trailing bytes must be rejected.
	_, err = DecodeTransactionError([]byte{0, 0, 0, 0, 0xff})
	require.Error(t, err)

	// Truncated payloads must error.
	_, err = DecodeTransactionError([]byte{8, 0, 0, 0})
	require.Error(t, err)

	// Unknown JSON variant names must error.
	var te TransactionError
	require.Error(t, te.UnmarshalJSON([]byte(`"NotARealVariant"`)))
	require.Error(t, te.UnmarshalJSON([]byte(`{"NotARealVariant":1}`)))
}

// TestTransactionErrorAsGoError pins the error-interface integration:
// TransactionError values travel through Go error plumbing.
func TestTransactionErrorAsGoError(t *testing.T) {
	var err error = &TransactionError{
		Type:             TxErrInstructionError,
		InstructionIndex: 0,
		InstructionError: &InstructionError{Type: InstrErrCustom, Custom: 42},
	}
	assert.Equal(t, "Error processing Instruction 0: custom program error: 0x2a", err.Error())

	var te *TransactionError
	require.ErrorAs(t, err, &te)
	assert.Equal(t, TxErrInstructionError, te.Type)
}
